   
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:  []
      # - ${KEYCLOAK_PORT}:8080
    networks:
      - public-network

networks:
  public-network:
    external: true
      

