services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports: []
      # - "${MINIO_PORT}:9000"
      # - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - public-network

networks:
  public-network:
    external: true