services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/d–∞ta:/root/redis
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=${REDIS_DATABASES}
    networks:
      - public-network

networks:
  public-network:
   external: true
     